### ISSUE TITLE
Enforce labeling rules

### ISSUE THREAD

**Issue by TravisEz13** [probot/ideas#93]
We require that one of a set of labels are applied.

Basically we require that a label that starts with `cl-` be applied before a PR is merged.

**Comment by cyberhck** [comment]
I should probably give this a try :)

**Comment by cyberhck** [comment]
https://github.com/apps/pull-request-label-enforcer hey, do you care to give this a try?

**Comment by cyberhck** [comment]
you do need a configuration file at `.github/pr_labels.yml`
```yml
invalidStatus: "pending"
labelRule:
  endsWith:
    - "g"
  values:
    - "bug"
    - "enhancement"
```
